#!/bin/bash

#
DIR=/home/kaushal-pi/Documents
#
#
#cd /home/kaushal-pi/Documents
cd $DIR || exit
#
#cd /usr/src
git clone git@github.com:kaushal-gawri/usap-assignment-2
#
#cd /usr/src
#
git clone --depth=1 https://github.com/raspberrypi/linux
#
sudo apt install raspberrypi-kernel-headers build-essential bc git wget bison flex libssl-dev make
#
cd linux || exit
#
verify KERNEL=kernel7l
#
make bcm2711_defconfig
#
sudo apt-get install qt5-\*-dev
#
make menuconfig
#
#
#sudo cp usr/src/usap-assignment-2/.config /usr/src/linux
sudo cp $DIR/usap-assignment-2/.config $DIR/linux
#
#
#change this to the github cloned directory
#./home/kaushal-pi/usap-assignment-2/first-script.sh &
#cd ..
#cd usap-assignment-2
cd $DIR/usap-assignment-2 || exit
./first-script.sh &
pid=$!
./second-monitor.sh &
pid1=$!
#
#cd ..
#cd linux
cd $DIR/linux || exit
#
#
make -j4 zImage modules dtbs
#
kill -s USR1 $pid
#
kill -s USR2 $pid1
#
#
sudo make modules_install
#
sudo cp /boot/kernel7.img /tmp/
#
sudo mkdir /mnt/new-boot
#
sudo mkdir /mnt/new-boot-files
#
sudo mount /dev/mcblk0p1 /mnt/new-boot
#
sudo mount /dev/mcblk0p2 /mnt/new-boot-files
#
sudo cp /mnt/new-boot/kernel7.img -/
#
#
sudo cp arch/arm/boot/dts/*.dtb /boot/
#
sudo cp arch/arm/boot/dts/overlays/*.dtb* /boot/overlays/
#
sudo cp arch/arm/boot/dts/overlays/README /boot/overlays/
#
sudo cp arch/arm/boot/zImage /boot/myKernel.img
#
sudo reboot


